### ISSUE TITLE
verify-single command doesn't work

### ISSUE THREAD

**Issue by foreverqihe** [arthurnn/minitest-emacs#39] opened 2018-08-23 05:00 UTC
Hi,
I found the verify single command doesn't work. Details:

The test name generated by minitest is: "test_0001_should create a new index file"
However, minitest-emacs creates below parameter which doesn't work
"-n/should_create_a_new_index_file/"

I tried with Intellij and it outputs:
"--name=/test_\d+_should create a new index file/"

This should be easy to fix but I am not familiar with elisp. Could you fix it or let me know where to fix it, I'll raise a PR?

Kind Regards,
He Qi

**Comment by gcentauri** [comment] 2019-09-27 21:19
@foreverqihe - Hi He Qi, I know it has been over a year, but I've also run into this issue recently.

Mine seemed to be caused by a different problem, where if a test string started with "#", it would produce a name prefixed with an underscore that does not match.  Removing the "#", like "create does x..." rather than "#create does x..."

I'm hoping to work on the issue, so if you're still using the package and can provide any other data that might be helpful :)

**Comment by gcentauri** [comment] 2020-09-17 17:32
verify-single still has issues in certain contexts, but it does work sometimes. closing this issue in favor of the more specific existing ones

**Closed by gcentauri** 2020-09-17 17:32 UTC
